name = "Strata II"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/Programazing/hugo-strata-theme-II/blob/master/LICENSE.md"
description = "A responsive and minimal single-page portfolio with blogging capabilities."
homepage = "//github.com/Programazing/hugo-strata-theme-II"
tags = ["image gallery", "contact form", "google analytics", "customizable", "blog", "single-page"]
features = ["", ""]
min_version = 0.16

[author]
  name = "Programazing"
  homepage = "//github.com/Programazing"

# If porting an existing theme
[original]
  name = "AJ"
  homepage = "//html5up.net/"
  repo = ""
